close all
clearvars
cd(fileparts(which(mfilename)));
load('data1_gen.mat')
save('cell1_gen.mat','simple1_trial1_genpot','simple1_trial1_spindices','simple1_trial1_peaks','simple1_trial1_thresholds','simple1_trial2_genpot','simple1_trial2_spindices','simple1_trial2_peaks','simple1_trial2_thresholds','simple1_trial3_genpot','simple1_trial3_spindices','simple1_trial3_peaks','simple1_trial3_thresholds','simple1_trial4_genpot','simple1_trial4_spindices','simple1_trial4_peaks','simple1_trial4_thresholds','simple1_trial5_genpot','simple1_trial5_spindices','simple1_trial5_peaks','simple1_trial5_thresholds','simple1_trial6_genpot','simple1_trial6_spindices','simple1_trial6_peaks','simple1_trial6_thresholds')
save('cell2_gen.mat','simple2_trial1_genpot','simple2_trial1_spindices','simple2_trial1_peaks','simple2_trial1_thresholds','simple2_trial2_genpot','simple2_trial2_spindices','simple2_trial2_peaks','simple2_trial2_thresholds','simple2_trial3_genpot','simple2_trial3_spindices','simple2_trial3_peaks','simple2_trial3_thresholds','simple2_trial4_genpot','simple2_trial4_spindices','simple2_trial4_peaks','simple2_trial4_thresholds','simple2_trial5_genpot','simple2_trial5_spindices','simple2_trial5_peaks','simple2_trial5_thresholds')
save('cell3_gen.mat','simple3_trial1_genpot','simple3_trial1_spindices','simple3_trial1_peaks','simple3_trial1_thresholds','simple3_trial2_genpot','simple3_trial2_spindices','simple3_trial2_peaks','simple3_trial2_thresholds','simple3_trial3_genpot','simple3_trial3_spindices','simple3_trial3_peaks','simple3_trial3_thresholds','simple3_trial4_genpot','simple3_trial4_spindices','simple3_trial4_peaks','simple3_trial4_thresholds','simple3_trial5_genpot','simple3_trial5_spindices','simple3_trial5_peaks','simple3_trial5_thresholds')
save('cell4_gen.mat','simple4_trial1_genpot','simple4_trial1_spindices','simple4_trial1_peaks','simple4_trial1_thresholds','simple4_trial2_genpot','simple4_trial2_spindices','simple4_trial2_peaks','simple4_trial2_thresholds','simple4_trial3_genpot','simple4_trial3_spindices','simple4_trial3_peaks','simple4_trial3_thresholds','simple4_trial4_genpot','simple4_trial4_spindices','simple4_trial4_peaks','simple4_trial4_thresholds','simple4_trial5_genpot','simple4_trial5_spindices','simple4_trial5_peaks','simple4_trial5_thresholds')

